---
  - hosts: all
    pre_tasks:
    - name: Ensure apt-get is uptodate
      apt: update_cache=yes

    tasks:

    vars_files:
    - vars/drupal.yml

    roles:
    - ansible-role-drupal
