---
  - hosts: all
    pre_tasks:
    - name: Ensure apt-get is uptodate
      apt: update_cache=yes
    #todo: this should ideally be it's own role with template.
    # infact it might be better to use mailcatcher but look at this later
    - name: Get sendmail
      apt: name="sendmail" state="present"

    tasks:

    vars_files:
    - vars/drupal.yml

    roles:
    - ansible-role-drupal
